<?php
    return array(
        "home"=>array(
            "routename"=>"/",
            "file"=>"src/php/paginainicial"
        ),
        "home2"=>array(
            "routename"=>"/index.php",
            "file"=>"src/php/paginainicial"
        ),
        "atendimento"=>array(
            "routename"=>"/atendimento",
            "file"=>"src/php/atendimento/atendimento"
        ),
        "chat"=>array(
            "routename"=>"/chat",
            "file"=>"src/php/chat/index"
        ),
        "relatorios"=>array(
            "routename"=>"/autentica",
            "file"=>"src/php/relatorios/ChamaRelatorios"
        ),
        "autentica"=>array(
        	"routename"=>"/relatorios",
        	"file"=>"src/php/relatorios/relatorios"
        ),
        "logout"=>array(
        	"routename"=>"/logout",
        	"file"=>"src/php/logout"
        ),
        "alimentaFila"=>array(
        	"routename"=>"/alimentaFila",
        	"file"=>"src/php/alimentaFila/alimentaFila"
        ),
        "encerraAtendimento"=>array(
        	"routename"=>"/encerraAtendimento",
        	"file"=>"src/php/atendimento/encerraAtendimento"
        ),
        "imprimeFicha"=>array(
        	"routename"=>"/imprimeFicha",
        	"file"=>"src/php/alimentaFila/imprimeFicha"
        )
    );